version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-auth-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth-network

volumes:
  postgres_data:

networks:
  auth-network:
